# This file is generated by the LocalizationKeyGenerator class. Do not modify it manually.

from GuiFramework.utilities.localization.localization_key import LocalizationKey


class LocKeys:

    class AutoDriveTranslationTool:
        LOADING_SCREEN_MESSAGE = LocalizationKey("AutoDriveTranslationTool.loading_screen_message")

        class Tabs:
            DICTIONARIES = LocalizationKey("AutoDriveTranslationTool.Tabs.dictionaries")
            OPTIONS = LocalizationKey("AutoDriveTranslationTool.Tabs.options")
            TRANSLATION = LocalizationKey("AutoDriveTranslationTool.Tabs.translation")

    class DictionariesFrame:

        class Widgets:

            class Buttons:

                class add_language:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.add_language.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.add_language.tooltip")

                class clear_edit_box:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.clear_edit_box.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.clear_edit_box.tooltip")

                class delete_dic_file:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.delete_dic_file.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.delete_dic_file.tooltip")

                class delete_language:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.delete_language.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.delete_language.tooltip")

                class load_dic_file:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.load_dic_file.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.load_dic_file.tooltip")

                class load_template:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.load_template.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.load_template.tooltip")

                class save_dic_file:
                    TEXT = LocalizationKey("DictionariesFrame.Widgets.Buttons.save_dic_file.text")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Buttons.save_dic_file.tooltip")

            class Entries:

                class new_language:
                    PLACEHOLDER = LocalizationKey("DictionariesFrame.Widgets.Entries.new_language.placeholder")
                    TOOLTIP = LocalizationKey("DictionariesFrame.Widgets.Entries.new_language.tooltip")

            class Popups:

                class ClearTextbox:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.ClearTextbox.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.ClearTextbox.title")

                class DeleteDicFile:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.DeleteDicFile.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.DeleteDicFile.title")

                class DeleteLanguage:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.DeleteLanguage.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.DeleteLanguage.title")

                class InvalidFileName:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.InvalidFileName.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.InvalidFileName.title")

                class InvalidLanguageName:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.InvalidLanguageName.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.InvalidLanguageName.title")

                class LanguageAlreadyExists:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.LanguageAlreadyExists.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.LanguageAlreadyExists.title")

                class LoadDicTemplate:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.LoadDicTemplate.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.LoadDicTemplate.title")

                class SaveAsNewDicFile:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.SaveAsNewDicFile.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.SaveAsNewDicFile.title")

                class SaveToDicFile:
                    MESSAGE = LocalizationKey("DictionariesFrame.Widgets.Popups.SaveToDicFile.message")
                    TITLE = LocalizationKey("DictionariesFrame.Widgets.Popups.SaveToDicFile.title")

    class Generic:

        class Languages:
            ENGLISH = LocalizationKey("Generic.Languages.english")
            FRENCH = LocalizationKey("Generic.Languages.french")
            GERMAN = LocalizationKey("Generic.Languages.german")
            ITALIAN = LocalizationKey("Generic.Languages.italian")
            RUSSIAN = LocalizationKey("Generic.Languages.russian")
            SPANISH = LocalizationKey("Generic.Languages.spanish")

        class UI:

            class ColorThemes:
                AD_GREEN = LocalizationKey("Generic.UI.ColorThemes.ad-green")
                BLUE = LocalizationKey("Generic.UI.ColorThemes.blue")
                DARK_BLUE = LocalizationKey("Generic.UI.ColorThemes.dark-blue")
                GREEN = LocalizationKey("Generic.UI.ColorThemes.green")

            class Themes:
                DARK = LocalizationKey("Generic.UI.Themes.dark")
                LIGHT = LocalizationKey("Generic.UI.Themes.light")
                SYSTEM = LocalizationKey("Generic.UI.Themes.system")

        class Widgets:

            class Popup:

                class Buttons:
                    ABORT = LocalizationKey("Generic.Widgets.Popup.Buttons.abort")
                    ACCEPT = LocalizationKey("Generic.Widgets.Popup.Buttons.accept")
                    BACK = LocalizationKey("Generic.Widgets.Popup.Buttons.back")
                    CANCEL = LocalizationKey("Generic.Widgets.Popup.Buttons.cancel")
                    CLOSE = LocalizationKey("Generic.Widgets.Popup.Buttons.close")
                    CONFIRM = LocalizationKey("Generic.Widgets.Popup.Buttons.confirm")
                    DELETE = LocalizationKey("Generic.Widgets.Popup.Buttons.delete")
                    EDIT = LocalizationKey("Generic.Widgets.Popup.Buttons.edit")
                    FINISH = LocalizationKey("Generic.Widgets.Popup.Buttons.finish")
                    IGNORE = LocalizationKey("Generic.Widgets.Popup.Buttons.ignore")
                    NEXT = LocalizationKey("Generic.Widgets.Popup.Buttons.next")
                    NO = LocalizationKey("Generic.Widgets.Popup.Buttons.no")
                    OK = LocalizationKey("Generic.Widgets.Popup.Buttons.ok")
                    RETRY = LocalizationKey("Generic.Widgets.Popup.Buttons.retry")
                    SAVE = LocalizationKey("Generic.Widgets.Popup.Buttons.save")
                    SUBMIT = LocalizationKey("Generic.Widgets.Popup.Buttons.submit")
                    YES = LocalizationKey("Generic.Widgets.Popup.Buttons.yes")

            class TreeView:

                class Buttons:

                    class collapse_all:
                        ICON = LocalizationKey("Generic.Widgets.TreeView.Buttons.collapse_all.icon")
                        TEXT = LocalizationKey("Generic.Widgets.TreeView.Buttons.collapse_all.text")
                        TOOLTIP = LocalizationKey("Generic.Widgets.TreeView.Buttons.collapse_all.tooltip")

                    class deselect_all:
                        ICON = LocalizationKey("Generic.Widgets.TreeView.Buttons.deselect_all.icon")
                        TEXT = LocalizationKey("Generic.Widgets.TreeView.Buttons.deselect_all.text")
                        TOOLTIP = LocalizationKey("Generic.Widgets.TreeView.Buttons.deselect_all.tooltip")

                    class expand_all:
                        ICON = LocalizationKey("Generic.Widgets.TreeView.Buttons.expand_all.icon")
                        TEXT = LocalizationKey("Generic.Widgets.TreeView.Buttons.expand_all.text")
                        TOOLTIP = LocalizationKey("Generic.Widgets.TreeView.Buttons.expand_all.tooltip")

                    class open_explorer:
                        ICON = LocalizationKey("Generic.Widgets.TreeView.Buttons.open_explorer.icon")
                        TEXT = LocalizationKey("Generic.Widgets.TreeView.Buttons.open_explorer.text")
                        TOOLTIP = LocalizationKey("Generic.Widgets.TreeView.Buttons.open_explorer.tooltip")

                    class refresh:
                        ICON = LocalizationKey("Generic.Widgets.TreeView.Buttons.refresh.icon")
                        TEXT = LocalizationKey("Generic.Widgets.TreeView.Buttons.refresh.text")
                        TOOLTIP = LocalizationKey("Generic.Widgets.TreeView.Buttons.refresh.tooltip")

                    class select_all:
                        ICON = LocalizationKey("Generic.Widgets.TreeView.Buttons.select_all.icon")
                        TEXT = LocalizationKey("Generic.Widgets.TreeView.Buttons.select_all.text")
                        TOOLTIP = LocalizationKey("Generic.Widgets.TreeView.Buttons.select_all.tooltip")

    class OptionsFrame:

        class Widgets:

            class Buttons:

                class reset_everything:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_everything.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_everything.tooltip")

                class reset_ui_appearance_settings:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_ui_appearance_settings.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_ui_appearance_settings.tooltip")

                class reset_window_position:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_window_position.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_window_position.tooltip")

                class reset_window_settings:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_window_settings.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_window_settings.tooltip")

                class reset_window_size:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_window_size.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Buttons.reset_window_size.tooltip")

            class Checkboxes:

                class center_window_on_startup:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Checkboxes.center_window_on_startup.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Checkboxes.center_window_on_startup.tooltip")

                class save_window_position:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Checkboxes.save_window_position.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Checkboxes.save_window_position.tooltip")

                class save_window_size:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Checkboxes.save_window_size.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Checkboxes.save_window_size.tooltip")

                class use_high_dpi_scaling:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Checkboxes.use_high_dpi_scaling.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Checkboxes.use_high_dpi_scaling.tooltip")

                class whole_word_replacement:
                    TEXT = LocalizationKey("OptionsFrame.Widgets.Checkboxes.whole_word_replacement.text")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.Checkboxes.whole_word_replacement.tooltip")

            class Labels:
                TRANSLATION_SETTINGS = LocalizationKey("OptionsFrame.Widgets.Labels.translation_settings")
                UI_APPEARANCE_SETTINGS = LocalizationKey("OptionsFrame.Widgets.Labels.ui_appearance_settings")
                UI_COLOR_THEME = LocalizationKey("OptionsFrame.Widgets.Labels.ui_color_theme")
                UI_LANGUAGE = LocalizationKey("OptionsFrame.Widgets.Labels.ui_language")
                UI_THEME = LocalizationKey("OptionsFrame.Widgets.Labels.ui_theme")
                WINDOW_SETTINGS = LocalizationKey("OptionsFrame.Widgets.Labels.window_settings")

            class OptionMenus:

                class ui_color_theme:
                    PLACEHOLDER = LocalizationKey("OptionsFrame.Widgets.OptionMenus.ui_color_theme.placeholder")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.OptionMenus.ui_color_theme.tooltip")

                class ui_language:
                    PLACEHOLDER = LocalizationKey("OptionsFrame.Widgets.OptionMenus.ui_language.placeholder")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.OptionMenus.ui_language.tooltip")

                class ui_theme:
                    PLACEHOLDER = LocalizationKey("OptionsFrame.Widgets.OptionMenus.ui_theme.placeholder")
                    TOOLTIP = LocalizationKey("OptionsFrame.Widgets.OptionMenus.ui_theme.tooltip")

    class TranslationFrame:

        class Widgets:

            class Buttons:

                class clear_console:
                    ICON = LocalizationKey("TranslationFrame.Widgets.Buttons.clear_console.icon")
                    TEXT = LocalizationKey("TranslationFrame.Widgets.Buttons.clear_console.text")
                    TOOLTIP = LocalizationKey("TranslationFrame.Widgets.Buttons.clear_console.tooltip")

                class open_output_dir:
                    ICON = LocalizationKey("TranslationFrame.Widgets.Buttons.open_output_dir.icon")
                    TEXT = LocalizationKey("TranslationFrame.Widgets.Buttons.open_output_dir.text")
                    TOOLTIP = LocalizationKey("TranslationFrame.Widgets.Buttons.open_output_dir.tooltip")

                class translate:
                    TEXT = LocalizationKey("TranslationFrame.Widgets.Buttons.translate.text")
                    TOOLTIP = LocalizationKey("TranslationFrame.Widgets.Buttons.translate.tooltip")

            class Popups:

                class StartTranslation:
                    MESSAGE = LocalizationKey("TranslationFrame.Widgets.Popups.StartTranslation.message")
                    TITLE = LocalizationKey("TranslationFrame.Widgets.Popups.StartTranslation.title")

            class TreeView:

                class dictionaries:

                    class Buttons:

                        class deselect_all:
                            TOOLTIP = LocalizationKey("TranslationFrame.Widgets.TreeView.dictionaries.Buttons.deselect_all.tooltip")

                        class open_explorer:
                            TOOLTIP = LocalizationKey("TranslationFrame.Widgets.TreeView.dictionaries.Buttons.open_explorer.tooltip")

                        class select_all:
                            TOOLTIP = LocalizationKey("TranslationFrame.Widgets.TreeView.dictionaries.Buttons.select_all.tooltip")

                class input:

                    class Buttons:

                        class deselect_all:
                            TOOLTIP = LocalizationKey("TranslationFrame.Widgets.TreeView.input.Buttons.deselect_all.tooltip")

                        class open_explorer:
                            TOOLTIP = LocalizationKey("TranslationFrame.Widgets.TreeView.input.Buttons.open_explorer.tooltip")

                        class select_all:
                            TOOLTIP = LocalizationKey("TranslationFrame.Widgets.TreeView.input.Buttons.select_all.tooltip")

    class TranslationScript:
        AVG_TRANSLATIONS_PER_FILE = LocalizationKey("TranslationScript.avg_translations_per_file")
        ERROR_INVALID_DICTIONARY = LocalizationKey("TranslationScript.error_invalid_dictionary")
        ERROR_INVALID_INPUT_FILE = LocalizationKey("TranslationScript.error_invalid_input_file")
        ERROR_PARSING_XML_FILE = LocalizationKey("TranslationScript.error_parsing_xml_file")
        FILE_BASED_STATISTICS = LocalizationKey("TranslationScript.file_based_statistics")
        FILE_LANGUAGE_TRANSLATIONS = LocalizationKey("TranslationScript.file_language_translations")
        FILE_TRANSLATIONS = LocalizationKey("TranslationScript.file_translations")
        LANGUAGE_BASED_STATISTICS = LocalizationKey("TranslationScript.language_based_statistics")
        LANGUAGE_TRANSLATION_COUNT = LocalizationKey("TranslationScript.language_translation_count")
        TOTAL_FILES_TRANSLATED = LocalizationKey("TranslationScript.total_files_translated")
        TOTAL_TIME_TAKEN = LocalizationKey("TranslationScript.total_time_taken")
        TOTAL_TRANSLATIONS_MADE = LocalizationKey("TranslationScript.total_translations_made")
        TRANSLATION_BASED_STATISTICS = LocalizationKey("TranslationScript.translation_based_statistics")
        TRANSLATION_SUMMARY = LocalizationKey("TranslationScript.translation_summary")
        UNIQUE_WORDS_TRANSLATED = LocalizationKey("TranslationScript.unique_words_translated")
        WORD_TRANSLATION_COUNT = LocalizationKey("TranslationScript.word_translation_count")
